//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WmcSoft.Windows.Forms {
    using System;
    using System.Windows.Forms;
    
    public partial class CustomProfessionalColors {
        public virtual System.Drawing.Color ButtonSelectedHighlight {
            get {
                return ((System.Drawing.Color)(this.GetColor("ButtonSelectedHighlight", System.Windows.Forms.ProfessionalColors.ButtonSelectedHighlight)));
            }
            set {
                this.SetColor("ButtonSelectedHighlight", value, System.Windows.Forms.ProfessionalColors.ButtonSelectedHighlight);
            }
        }
        public virtual System.Drawing.Color ButtonSelectedHighlightBorder {
            get {
                return ((System.Drawing.Color)(this.GetColor("ButtonSelectedHighlightBorder", System.Windows.Forms.ProfessionalColors.ButtonSelectedHighlightBorder)));
            }
            set {
                this.SetColor("ButtonSelectedHighlightBorder", value, System.Windows.Forms.ProfessionalColors.ButtonSelectedHighlightBorder);
            }
        }
        public virtual System.Drawing.Color ButtonPressedHighlight {
            get {
                return ((System.Drawing.Color)(this.GetColor("ButtonPressedHighlight", System.Windows.Forms.ProfessionalColors.ButtonPressedHighlight)));
            }
            set {
                this.SetColor("ButtonPressedHighlight", value, System.Windows.Forms.ProfessionalColors.ButtonPressedHighlight);
            }
        }
        public virtual System.Drawing.Color ButtonPressedHighlightBorder {
            get {
                return ((System.Drawing.Color)(this.GetColor("ButtonPressedHighlightBorder", System.Windows.Forms.ProfessionalColors.ButtonPressedHighlightBorder)));
            }
            set {
                this.SetColor("ButtonPressedHighlightBorder", value, System.Windows.Forms.ProfessionalColors.ButtonPressedHighlightBorder);
            }
        }
        public virtual System.Drawing.Color ButtonCheckedHighlight {
            get {
                return ((System.Drawing.Color)(this.GetColor("ButtonCheckedHighlight", System.Windows.Forms.ProfessionalColors.ButtonCheckedHighlight)));
            }
            set {
                this.SetColor("ButtonCheckedHighlight", value, System.Windows.Forms.ProfessionalColors.ButtonCheckedHighlight);
            }
        }
        public virtual System.Drawing.Color ButtonCheckedHighlightBorder {
            get {
                return ((System.Drawing.Color)(this.GetColor("ButtonCheckedHighlightBorder", System.Windows.Forms.ProfessionalColors.ButtonCheckedHighlightBorder)));
            }
            set {
                this.SetColor("ButtonCheckedHighlightBorder", value, System.Windows.Forms.ProfessionalColors.ButtonCheckedHighlightBorder);
            }
        }
        public virtual System.Drawing.Color ButtonPressedBorder {
            get {
                return ((System.Drawing.Color)(this.GetColor("ButtonPressedBorder", System.Windows.Forms.ProfessionalColors.ButtonPressedBorder)));
            }
            set {
                this.SetColor("ButtonPressedBorder", value, System.Windows.Forms.ProfessionalColors.ButtonPressedBorder);
            }
        }
        public virtual System.Drawing.Color ButtonSelectedBorder {
            get {
                return ((System.Drawing.Color)(this.GetColor("ButtonSelectedBorder", System.Windows.Forms.ProfessionalColors.ButtonSelectedBorder)));
            }
            set {
                this.SetColor("ButtonSelectedBorder", value, System.Windows.Forms.ProfessionalColors.ButtonSelectedBorder);
            }
        }
        public virtual System.Drawing.Color ButtonCheckedGradientBegin {
            get {
                return ((System.Drawing.Color)(this.GetColor("ButtonCheckedGradientBegin", System.Windows.Forms.ProfessionalColors.ButtonCheckedGradientBegin)));
            }
            set {
                this.SetColor("ButtonCheckedGradientBegin", value, System.Windows.Forms.ProfessionalColors.ButtonCheckedGradientBegin);
            }
        }
        public virtual System.Drawing.Color ButtonCheckedGradientMiddle {
            get {
                return ((System.Drawing.Color)(this.GetColor("ButtonCheckedGradientMiddle", System.Windows.Forms.ProfessionalColors.ButtonCheckedGradientMiddle)));
            }
            set {
                this.SetColor("ButtonCheckedGradientMiddle", value, System.Windows.Forms.ProfessionalColors.ButtonCheckedGradientMiddle);
            }
        }
        public virtual System.Drawing.Color ButtonCheckedGradientEnd {
            get {
                return ((System.Drawing.Color)(this.GetColor("ButtonCheckedGradientEnd", System.Windows.Forms.ProfessionalColors.ButtonCheckedGradientEnd)));
            }
            set {
                this.SetColor("ButtonCheckedGradientEnd", value, System.Windows.Forms.ProfessionalColors.ButtonCheckedGradientEnd);
            }
        }
        public virtual System.Drawing.Color ButtonSelectedGradientBegin {
            get {
                return ((System.Drawing.Color)(this.GetColor("ButtonSelectedGradientBegin", System.Windows.Forms.ProfessionalColors.ButtonSelectedGradientBegin)));
            }
            set {
                this.SetColor("ButtonSelectedGradientBegin", value, System.Windows.Forms.ProfessionalColors.ButtonSelectedGradientBegin);
            }
        }
        public virtual System.Drawing.Color ButtonSelectedGradientMiddle {
            get {
                return ((System.Drawing.Color)(this.GetColor("ButtonSelectedGradientMiddle", System.Windows.Forms.ProfessionalColors.ButtonSelectedGradientMiddle)));
            }
            set {
                this.SetColor("ButtonSelectedGradientMiddle", value, System.Windows.Forms.ProfessionalColors.ButtonSelectedGradientMiddle);
            }
        }
        public virtual System.Drawing.Color ButtonSelectedGradientEnd {
            get {
                return ((System.Drawing.Color)(this.GetColor("ButtonSelectedGradientEnd", System.Windows.Forms.ProfessionalColors.ButtonSelectedGradientEnd)));
            }
            set {
                this.SetColor("ButtonSelectedGradientEnd", value, System.Windows.Forms.ProfessionalColors.ButtonSelectedGradientEnd);
            }
        }
        public virtual System.Drawing.Color ButtonPressedGradientBegin {
            get {
                return ((System.Drawing.Color)(this.GetColor("ButtonPressedGradientBegin", System.Windows.Forms.ProfessionalColors.ButtonPressedGradientBegin)));
            }
            set {
                this.SetColor("ButtonPressedGradientBegin", value, System.Windows.Forms.ProfessionalColors.ButtonPressedGradientBegin);
            }
        }
        public virtual System.Drawing.Color ButtonPressedGradientMiddle {
            get {
                return ((System.Drawing.Color)(this.GetColor("ButtonPressedGradientMiddle", System.Windows.Forms.ProfessionalColors.ButtonPressedGradientMiddle)));
            }
            set {
                this.SetColor("ButtonPressedGradientMiddle", value, System.Windows.Forms.ProfessionalColors.ButtonPressedGradientMiddle);
            }
        }
        public virtual System.Drawing.Color ButtonPressedGradientEnd {
            get {
                return ((System.Drawing.Color)(this.GetColor("ButtonPressedGradientEnd", System.Windows.Forms.ProfessionalColors.ButtonPressedGradientEnd)));
            }
            set {
                this.SetColor("ButtonPressedGradientEnd", value, System.Windows.Forms.ProfessionalColors.ButtonPressedGradientEnd);
            }
        }
        public virtual System.Drawing.Color CheckBackground {
            get {
                return ((System.Drawing.Color)(this.GetColor("CheckBackground", System.Windows.Forms.ProfessionalColors.CheckBackground)));
            }
            set {
                this.SetColor("CheckBackground", value, System.Windows.Forms.ProfessionalColors.CheckBackground);
            }
        }
        public virtual System.Drawing.Color CheckSelectedBackground {
            get {
                return ((System.Drawing.Color)(this.GetColor("CheckSelectedBackground", System.Windows.Forms.ProfessionalColors.CheckSelectedBackground)));
            }
            set {
                this.SetColor("CheckSelectedBackground", value, System.Windows.Forms.ProfessionalColors.CheckSelectedBackground);
            }
        }
        public virtual System.Drawing.Color CheckPressedBackground {
            get {
                return ((System.Drawing.Color)(this.GetColor("CheckPressedBackground", System.Windows.Forms.ProfessionalColors.CheckPressedBackground)));
            }
            set {
                this.SetColor("CheckPressedBackground", value, System.Windows.Forms.ProfessionalColors.CheckPressedBackground);
            }
        }
        public virtual System.Drawing.Color GripDark {
            get {
                return ((System.Drawing.Color)(this.GetColor("GripDark", System.Windows.Forms.ProfessionalColors.GripDark)));
            }
            set {
                this.SetColor("GripDark", value, System.Windows.Forms.ProfessionalColors.GripDark);
            }
        }
        public virtual System.Drawing.Color GripLight {
            get {
                return ((System.Drawing.Color)(this.GetColor("GripLight", System.Windows.Forms.ProfessionalColors.GripLight)));
            }
            set {
                this.SetColor("GripLight", value, System.Windows.Forms.ProfessionalColors.GripLight);
            }
        }
        public virtual System.Drawing.Color ImageMarginGradientBegin {
            get {
                return ((System.Drawing.Color)(this.GetColor("ImageMarginGradientBegin", System.Windows.Forms.ProfessionalColors.ImageMarginGradientBegin)));
            }
            set {
                this.SetColor("ImageMarginGradientBegin", value, System.Windows.Forms.ProfessionalColors.ImageMarginGradientBegin);
            }
        }
        public virtual System.Drawing.Color ImageMarginGradientMiddle {
            get {
                return ((System.Drawing.Color)(this.GetColor("ImageMarginGradientMiddle", System.Windows.Forms.ProfessionalColors.ImageMarginGradientMiddle)));
            }
            set {
                this.SetColor("ImageMarginGradientMiddle", value, System.Windows.Forms.ProfessionalColors.ImageMarginGradientMiddle);
            }
        }
        public virtual System.Drawing.Color ImageMarginGradientEnd {
            get {
                return ((System.Drawing.Color)(this.GetColor("ImageMarginGradientEnd", System.Windows.Forms.ProfessionalColors.ImageMarginGradientEnd)));
            }
            set {
                this.SetColor("ImageMarginGradientEnd", value, System.Windows.Forms.ProfessionalColors.ImageMarginGradientEnd);
            }
        }
        public virtual System.Drawing.Color ImageMarginRevealedGradientBegin {
            get {
                return ((System.Drawing.Color)(this.GetColor("ImageMarginRevealedGradientBegin", System.Windows.Forms.ProfessionalColors.ImageMarginRevealedGradientBegin)));
            }
            set {
                this.SetColor("ImageMarginRevealedGradientBegin", value, System.Windows.Forms.ProfessionalColors.ImageMarginRevealedGradientBegin);
            }
        }
        public virtual System.Drawing.Color ImageMarginRevealedGradientMiddle {
            get {
                return ((System.Drawing.Color)(this.GetColor("ImageMarginRevealedGradientMiddle", System.Windows.Forms.ProfessionalColors.ImageMarginRevealedGradientMiddle)));
            }
            set {
                this.SetColor("ImageMarginRevealedGradientMiddle", value, System.Windows.Forms.ProfessionalColors.ImageMarginRevealedGradientMiddle);
            }
        }
        public virtual System.Drawing.Color ImageMarginRevealedGradientEnd {
            get {
                return ((System.Drawing.Color)(this.GetColor("ImageMarginRevealedGradientEnd", System.Windows.Forms.ProfessionalColors.ImageMarginRevealedGradientEnd)));
            }
            set {
                this.SetColor("ImageMarginRevealedGradientEnd", value, System.Windows.Forms.ProfessionalColors.ImageMarginRevealedGradientEnd);
            }
        }
        public virtual System.Drawing.Color MenuStripGradientBegin {
            get {
                return ((System.Drawing.Color)(this.GetColor("MenuStripGradientBegin", System.Windows.Forms.ProfessionalColors.MenuStripGradientBegin)));
            }
            set {
                this.SetColor("MenuStripGradientBegin", value, System.Windows.Forms.ProfessionalColors.MenuStripGradientBegin);
            }
        }
        public virtual System.Drawing.Color MenuStripGradientEnd {
            get {
                return ((System.Drawing.Color)(this.GetColor("MenuStripGradientEnd", System.Windows.Forms.ProfessionalColors.MenuStripGradientEnd)));
            }
            set {
                this.SetColor("MenuStripGradientEnd", value, System.Windows.Forms.ProfessionalColors.MenuStripGradientEnd);
            }
        }
        public virtual System.Drawing.Color MenuItemSelected {
            get {
                return ((System.Drawing.Color)(this.GetColor("MenuItemSelected", System.Windows.Forms.ProfessionalColors.MenuItemSelected)));
            }
            set {
                this.SetColor("MenuItemSelected", value, System.Windows.Forms.ProfessionalColors.MenuItemSelected);
            }
        }
        public virtual System.Drawing.Color MenuItemBorder {
            get {
                return ((System.Drawing.Color)(this.GetColor("MenuItemBorder", System.Windows.Forms.ProfessionalColors.MenuItemBorder)));
            }
            set {
                this.SetColor("MenuItemBorder", value, System.Windows.Forms.ProfessionalColors.MenuItemBorder);
            }
        }
        public virtual System.Drawing.Color MenuBorder {
            get {
                return ((System.Drawing.Color)(this.GetColor("MenuBorder", System.Windows.Forms.ProfessionalColors.MenuBorder)));
            }
            set {
                this.SetColor("MenuBorder", value, System.Windows.Forms.ProfessionalColors.MenuBorder);
            }
        }
        public virtual System.Drawing.Color MenuItemSelectedGradientBegin {
            get {
                return ((System.Drawing.Color)(this.GetColor("MenuItemSelectedGradientBegin", System.Windows.Forms.ProfessionalColors.MenuItemSelectedGradientBegin)));
            }
            set {
                this.SetColor("MenuItemSelectedGradientBegin", value, System.Windows.Forms.ProfessionalColors.MenuItemSelectedGradientBegin);
            }
        }
        public virtual System.Drawing.Color MenuItemSelectedGradientEnd {
            get {
                return ((System.Drawing.Color)(this.GetColor("MenuItemSelectedGradientEnd", System.Windows.Forms.ProfessionalColors.MenuItemSelectedGradientEnd)));
            }
            set {
                this.SetColor("MenuItemSelectedGradientEnd", value, System.Windows.Forms.ProfessionalColors.MenuItemSelectedGradientEnd);
            }
        }
        public virtual System.Drawing.Color MenuItemPressedGradientBegin {
            get {
                return ((System.Drawing.Color)(this.GetColor("MenuItemPressedGradientBegin", System.Windows.Forms.ProfessionalColors.MenuItemPressedGradientBegin)));
            }
            set {
                this.SetColor("MenuItemPressedGradientBegin", value, System.Windows.Forms.ProfessionalColors.MenuItemPressedGradientBegin);
            }
        }
        public virtual System.Drawing.Color MenuItemPressedGradientMiddle {
            get {
                return ((System.Drawing.Color)(this.GetColor("MenuItemPressedGradientMiddle", System.Windows.Forms.ProfessionalColors.MenuItemPressedGradientMiddle)));
            }
            set {
                this.SetColor("MenuItemPressedGradientMiddle", value, System.Windows.Forms.ProfessionalColors.MenuItemPressedGradientMiddle);
            }
        }
        public virtual System.Drawing.Color MenuItemPressedGradientEnd {
            get {
                return ((System.Drawing.Color)(this.GetColor("MenuItemPressedGradientEnd", System.Windows.Forms.ProfessionalColors.MenuItemPressedGradientEnd)));
            }
            set {
                this.SetColor("MenuItemPressedGradientEnd", value, System.Windows.Forms.ProfessionalColors.MenuItemPressedGradientEnd);
            }
        }
        public virtual System.Drawing.Color RaftingContainerGradientBegin {
            get {
                return ((System.Drawing.Color)(this.GetColor("RaftingContainerGradientBegin", System.Windows.Forms.ProfessionalColors.RaftingContainerGradientBegin)));
            }
            set {
                this.SetColor("RaftingContainerGradientBegin", value, System.Windows.Forms.ProfessionalColors.RaftingContainerGradientBegin);
            }
        }
        public virtual System.Drawing.Color RaftingContainerGradientEnd {
            get {
                return ((System.Drawing.Color)(this.GetColor("RaftingContainerGradientEnd", System.Windows.Forms.ProfessionalColors.RaftingContainerGradientEnd)));
            }
            set {
                this.SetColor("RaftingContainerGradientEnd", value, System.Windows.Forms.ProfessionalColors.RaftingContainerGradientEnd);
            }
        }
        public virtual System.Drawing.Color SeparatorDark {
            get {
                return ((System.Drawing.Color)(this.GetColor("SeparatorDark", System.Windows.Forms.ProfessionalColors.SeparatorDark)));
            }
            set {
                this.SetColor("SeparatorDark", value, System.Windows.Forms.ProfessionalColors.SeparatorDark);
            }
        }
        public virtual System.Drawing.Color SeparatorLight {
            get {
                return ((System.Drawing.Color)(this.GetColor("SeparatorLight", System.Windows.Forms.ProfessionalColors.SeparatorLight)));
            }
            set {
                this.SetColor("SeparatorLight", value, System.Windows.Forms.ProfessionalColors.SeparatorLight);
            }
        }
        public virtual System.Drawing.Color StatusStripGradientBegin {
            get {
                return ((System.Drawing.Color)(this.GetColor("StatusStripGradientBegin", System.Windows.Forms.ProfessionalColors.StatusStripGradientBegin)));
            }
            set {
                this.SetColor("StatusStripGradientBegin", value, System.Windows.Forms.ProfessionalColors.StatusStripGradientBegin);
            }
        }
        public virtual System.Drawing.Color StatusStripGradientEnd {
            get {
                return ((System.Drawing.Color)(this.GetColor("StatusStripGradientEnd", System.Windows.Forms.ProfessionalColors.StatusStripGradientEnd)));
            }
            set {
                this.SetColor("StatusStripGradientEnd", value, System.Windows.Forms.ProfessionalColors.StatusStripGradientEnd);
            }
        }
        public virtual System.Drawing.Color ToolStripBorder {
            get {
                return ((System.Drawing.Color)(this.GetColor("ToolStripBorder", System.Windows.Forms.ProfessionalColors.ToolStripBorder)));
            }
            set {
                this.SetColor("ToolStripBorder", value, System.Windows.Forms.ProfessionalColors.ToolStripBorder);
            }
        }
        public virtual System.Drawing.Color ToolStripDropDownBackground {
            get {
                return ((System.Drawing.Color)(this.GetColor("ToolStripDropDownBackground", System.Windows.Forms.ProfessionalColors.ToolStripDropDownBackground)));
            }
            set {
                this.SetColor("ToolStripDropDownBackground", value, System.Windows.Forms.ProfessionalColors.ToolStripDropDownBackground);
            }
        }
        public virtual System.Drawing.Color ToolStripGradientBegin {
            get {
                return ((System.Drawing.Color)(this.GetColor("ToolStripGradientBegin", System.Windows.Forms.ProfessionalColors.ToolStripGradientBegin)));
            }
            set {
                this.SetColor("ToolStripGradientBegin", value, System.Windows.Forms.ProfessionalColors.ToolStripGradientBegin);
            }
        }
        public virtual System.Drawing.Color ToolStripGradientMiddle {
            get {
                return ((System.Drawing.Color)(this.GetColor("ToolStripGradientMiddle", System.Windows.Forms.ProfessionalColors.ToolStripGradientMiddle)));
            }
            set {
                this.SetColor("ToolStripGradientMiddle", value, System.Windows.Forms.ProfessionalColors.ToolStripGradientMiddle);
            }
        }
        public virtual System.Drawing.Color ToolStripGradientEnd {
            get {
                return ((System.Drawing.Color)(this.GetColor("ToolStripGradientEnd", System.Windows.Forms.ProfessionalColors.ToolStripGradientEnd)));
            }
            set {
                this.SetColor("ToolStripGradientEnd", value, System.Windows.Forms.ProfessionalColors.ToolStripGradientEnd);
            }
        }
        public virtual System.Drawing.Color ToolStripContentPanelGradientBegin {
            get {
                return ((System.Drawing.Color)(this.GetColor("ToolStripContentPanelGradientBegin", System.Windows.Forms.ProfessionalColors.ToolStripContentPanelGradientBegin)));
            }
            set {
                this.SetColor("ToolStripContentPanelGradientBegin", value, System.Windows.Forms.ProfessionalColors.ToolStripContentPanelGradientBegin);
            }
        }
        public virtual System.Drawing.Color ToolStripContentPanelGradientEnd {
            get {
                return ((System.Drawing.Color)(this.GetColor("ToolStripContentPanelGradientEnd", System.Windows.Forms.ProfessionalColors.ToolStripContentPanelGradientEnd)));
            }
            set {
                this.SetColor("ToolStripContentPanelGradientEnd", value, System.Windows.Forms.ProfessionalColors.ToolStripContentPanelGradientEnd);
            }
        }
        public virtual System.Drawing.Color ToolStripPanelGradientBegin {
            get {
                return ((System.Drawing.Color)(this.GetColor("ToolStripPanelGradientBegin", System.Windows.Forms.ProfessionalColors.ToolStripPanelGradientBegin)));
            }
            set {
                this.SetColor("ToolStripPanelGradientBegin", value, System.Windows.Forms.ProfessionalColors.ToolStripPanelGradientBegin);
            }
        }
        public virtual System.Drawing.Color ToolStripPanelGradientEnd {
            get {
                return ((System.Drawing.Color)(this.GetColor("ToolStripPanelGradientEnd", System.Windows.Forms.ProfessionalColors.ToolStripPanelGradientEnd)));
            }
            set {
                this.SetColor("ToolStripPanelGradientEnd", value, System.Windows.Forms.ProfessionalColors.ToolStripPanelGradientEnd);
            }
        }
        public virtual System.Drawing.Color OverflowButtonGradientBegin {
            get {
                return ((System.Drawing.Color)(this.GetColor("OverflowButtonGradientBegin", System.Windows.Forms.ProfessionalColors.OverflowButtonGradientBegin)));
            }
            set {
                this.SetColor("OverflowButtonGradientBegin", value, System.Windows.Forms.ProfessionalColors.OverflowButtonGradientBegin);
            }
        }
        public virtual System.Drawing.Color OverflowButtonGradientMiddle {
            get {
                return ((System.Drawing.Color)(this.GetColor("OverflowButtonGradientMiddle", System.Windows.Forms.ProfessionalColors.OverflowButtonGradientMiddle)));
            }
            set {
                this.SetColor("OverflowButtonGradientMiddle", value, System.Windows.Forms.ProfessionalColors.OverflowButtonGradientMiddle);
            }
        }
        public virtual System.Drawing.Color OverflowButtonGradientEnd {
            get {
                return ((System.Drawing.Color)(this.GetColor("OverflowButtonGradientEnd", System.Windows.Forms.ProfessionalColors.OverflowButtonGradientEnd)));
            }
            set {
                this.SetColor("OverflowButtonGradientEnd", value, System.Windows.Forms.ProfessionalColors.OverflowButtonGradientEnd);
            }
        }
        public virtual System.Drawing.Color ButtonCheckedText {
            get {
                return ((System.Drawing.Color)(this.GetColor("ButtonCheckedText", System.Drawing.SystemColors.ControlText)));
            }
            set {
                this.SetColor("ButtonCheckedText", value, System.Drawing.SystemColors.ControlText);
            }
        }
        public virtual System.Drawing.Color ButtonPressedText {
            get {
                return ((System.Drawing.Color)(this.GetColor("ButtonPressedText", System.Drawing.SystemColors.ControlText)));
            }
            set {
                this.SetColor("ButtonPressedText", value, System.Drawing.SystemColors.ControlText);
            }
        }
        public virtual System.Drawing.Color ButtonSelectedText {
            get {
                return ((System.Drawing.Color)(this.GetColor("ButtonSelectedText", System.Drawing.SystemColors.ControlText)));
            }
            set {
                this.SetColor("ButtonSelectedText", value, System.Drawing.SystemColors.ControlText);
            }
        }
        public virtual System.Drawing.Color MenuItemText {
            get {
                return ((System.Drawing.Color)(this.GetColor("MenuItemText", System.Drawing.SystemColors.MenuText)));
            }
            set {
                this.SetColor("MenuItemText", value, System.Drawing.SystemColors.MenuText);
            }
        }
        public virtual System.Drawing.Color ToolStripDropDownText {
            get {
                return ((System.Drawing.Color)(this.GetColor("ToolStripDropDownText", System.Drawing.SystemColors.MenuText)));
            }
            set {
                this.SetColor("ToolStripDropDownText", value, System.Drawing.SystemColors.MenuText);
            }
        }
        public virtual System.Drawing.Color MenuItemPressedText {
            get {
                return ((System.Drawing.Color)(this.GetColor("MenuItemPressedText", System.Drawing.SystemColors.HighlightText)));
            }
            set {
                this.SetColor("MenuItemPressedText", value, System.Drawing.SystemColors.HighlightText);
            }
        }
        public virtual System.Drawing.Color MenuItemSelectedText {
            get {
                return ((System.Drawing.Color)(this.GetColor("MenuItemSelectedText", System.Drawing.SystemColors.HighlightText)));
            }
            set {
                this.SetColor("MenuItemSelectedText", value, System.Drawing.SystemColors.HighlightText);
            }
        }
        public virtual System.Drawing.Color StatusStripText {
            get {
                return ((System.Drawing.Color)(this.GetColor("StatusStripText", System.Drawing.SystemColors.ControlText)));
            }
            set {
                this.SetColor("StatusStripText", value, System.Drawing.SystemColors.ControlText);
            }
        }
        void ResetButtonSelectedHighlight() {
            this.ResetColor("ButtonSelectedHighlight", System.Windows.Forms.ProfessionalColors.ButtonSelectedHighlight);
        }
        bool ShouldSerializeButtonSelectedHighlight() {
            return this.ShouldSerializeColor("ButtonSelectedHighlight", System.Windows.Forms.ProfessionalColors.ButtonSelectedHighlight);
        }
        void ResetButtonSelectedHighlightBorder() {
            this.ResetColor("ButtonSelectedHighlightBorder", System.Windows.Forms.ProfessionalColors.ButtonSelectedHighlightBorder);
        }
        bool ShouldSerializeButtonSelectedHighlightBorder() {
            return this.ShouldSerializeColor("ButtonSelectedHighlightBorder", System.Windows.Forms.ProfessionalColors.ButtonSelectedHighlightBorder);
        }
        void ResetButtonPressedHighlight() {
            this.ResetColor("ButtonPressedHighlight", System.Windows.Forms.ProfessionalColors.ButtonPressedHighlight);
        }
        bool ShouldSerializeButtonPressedHighlight() {
            return this.ShouldSerializeColor("ButtonPressedHighlight", System.Windows.Forms.ProfessionalColors.ButtonPressedHighlight);
        }
        void ResetButtonPressedHighlightBorder() {
            this.ResetColor("ButtonPressedHighlightBorder", System.Windows.Forms.ProfessionalColors.ButtonPressedHighlightBorder);
        }
        bool ShouldSerializeButtonPressedHighlightBorder() {
            return this.ShouldSerializeColor("ButtonPressedHighlightBorder", System.Windows.Forms.ProfessionalColors.ButtonPressedHighlightBorder);
        }
        void ResetButtonCheckedHighlight() {
            this.ResetColor("ButtonCheckedHighlight", System.Windows.Forms.ProfessionalColors.ButtonCheckedHighlight);
        }
        bool ShouldSerializeButtonCheckedHighlight() {
            return this.ShouldSerializeColor("ButtonCheckedHighlight", System.Windows.Forms.ProfessionalColors.ButtonCheckedHighlight);
        }
        void ResetButtonCheckedHighlightBorder() {
            this.ResetColor("ButtonCheckedHighlightBorder", System.Windows.Forms.ProfessionalColors.ButtonCheckedHighlightBorder);
        }
        bool ShouldSerializeButtonCheckedHighlightBorder() {
            return this.ShouldSerializeColor("ButtonCheckedHighlightBorder", System.Windows.Forms.ProfessionalColors.ButtonCheckedHighlightBorder);
        }
        void ResetButtonPressedBorder() {
            this.ResetColor("ButtonPressedBorder", System.Windows.Forms.ProfessionalColors.ButtonPressedBorder);
        }
        bool ShouldSerializeButtonPressedBorder() {
            return this.ShouldSerializeColor("ButtonPressedBorder", System.Windows.Forms.ProfessionalColors.ButtonPressedBorder);
        }
        void ResetButtonSelectedBorder() {
            this.ResetColor("ButtonSelectedBorder", System.Windows.Forms.ProfessionalColors.ButtonSelectedBorder);
        }
        bool ShouldSerializeButtonSelectedBorder() {
            return this.ShouldSerializeColor("ButtonSelectedBorder", System.Windows.Forms.ProfessionalColors.ButtonSelectedBorder);
        }
        void ResetButtonCheckedGradientBegin() {
            this.ResetColor("ButtonCheckedGradientBegin", System.Windows.Forms.ProfessionalColors.ButtonCheckedGradientBegin);
        }
        bool ShouldSerializeButtonCheckedGradientBegin() {
            return this.ShouldSerializeColor("ButtonCheckedGradientBegin", System.Windows.Forms.ProfessionalColors.ButtonCheckedGradientBegin);
        }
        void ResetButtonCheckedGradientMiddle() {
            this.ResetColor("ButtonCheckedGradientMiddle", System.Windows.Forms.ProfessionalColors.ButtonCheckedGradientMiddle);
        }
        bool ShouldSerializeButtonCheckedGradientMiddle() {
            return this.ShouldSerializeColor("ButtonCheckedGradientMiddle", System.Windows.Forms.ProfessionalColors.ButtonCheckedGradientMiddle);
        }
        void ResetButtonCheckedGradientEnd() {
            this.ResetColor("ButtonCheckedGradientEnd", System.Windows.Forms.ProfessionalColors.ButtonCheckedGradientEnd);
        }
        bool ShouldSerializeButtonCheckedGradientEnd() {
            return this.ShouldSerializeColor("ButtonCheckedGradientEnd", System.Windows.Forms.ProfessionalColors.ButtonCheckedGradientEnd);
        }
        void ResetButtonSelectedGradientBegin() {
            this.ResetColor("ButtonSelectedGradientBegin", System.Windows.Forms.ProfessionalColors.ButtonSelectedGradientBegin);
        }
        bool ShouldSerializeButtonSelectedGradientBegin() {
            return this.ShouldSerializeColor("ButtonSelectedGradientBegin", System.Windows.Forms.ProfessionalColors.ButtonSelectedGradientBegin);
        }
        void ResetButtonSelectedGradientMiddle() {
            this.ResetColor("ButtonSelectedGradientMiddle", System.Windows.Forms.ProfessionalColors.ButtonSelectedGradientMiddle);
        }
        bool ShouldSerializeButtonSelectedGradientMiddle() {
            return this.ShouldSerializeColor("ButtonSelectedGradientMiddle", System.Windows.Forms.ProfessionalColors.ButtonSelectedGradientMiddle);
        }
        void ResetButtonSelectedGradientEnd() {
            this.ResetColor("ButtonSelectedGradientEnd", System.Windows.Forms.ProfessionalColors.ButtonSelectedGradientEnd);
        }
        bool ShouldSerializeButtonSelectedGradientEnd() {
            return this.ShouldSerializeColor("ButtonSelectedGradientEnd", System.Windows.Forms.ProfessionalColors.ButtonSelectedGradientEnd);
        }
        void ResetButtonPressedGradientBegin() {
            this.ResetColor("ButtonPressedGradientBegin", System.Windows.Forms.ProfessionalColors.ButtonPressedGradientBegin);
        }
        bool ShouldSerializeButtonPressedGradientBegin() {
            return this.ShouldSerializeColor("ButtonPressedGradientBegin", System.Windows.Forms.ProfessionalColors.ButtonPressedGradientBegin);
        }
        void ResetButtonPressedGradientMiddle() {
            this.ResetColor("ButtonPressedGradientMiddle", System.Windows.Forms.ProfessionalColors.ButtonPressedGradientMiddle);
        }
        bool ShouldSerializeButtonPressedGradientMiddle() {
            return this.ShouldSerializeColor("ButtonPressedGradientMiddle", System.Windows.Forms.ProfessionalColors.ButtonPressedGradientMiddle);
        }
        void ResetButtonPressedGradientEnd() {
            this.ResetColor("ButtonPressedGradientEnd", System.Windows.Forms.ProfessionalColors.ButtonPressedGradientEnd);
        }
        bool ShouldSerializeButtonPressedGradientEnd() {
            return this.ShouldSerializeColor("ButtonPressedGradientEnd", System.Windows.Forms.ProfessionalColors.ButtonPressedGradientEnd);
        }
        void ResetCheckBackground() {
            this.ResetColor("CheckBackground", System.Windows.Forms.ProfessionalColors.CheckBackground);
        }
        bool ShouldSerializeCheckBackground() {
            return this.ShouldSerializeColor("CheckBackground", System.Windows.Forms.ProfessionalColors.CheckBackground);
        }
        void ResetCheckSelectedBackground() {
            this.ResetColor("CheckSelectedBackground", System.Windows.Forms.ProfessionalColors.CheckSelectedBackground);
        }
        bool ShouldSerializeCheckSelectedBackground() {
            return this.ShouldSerializeColor("CheckSelectedBackground", System.Windows.Forms.ProfessionalColors.CheckSelectedBackground);
        }
        void ResetCheckPressedBackground() {
            this.ResetColor("CheckPressedBackground", System.Windows.Forms.ProfessionalColors.CheckPressedBackground);
        }
        bool ShouldSerializeCheckPressedBackground() {
            return this.ShouldSerializeColor("CheckPressedBackground", System.Windows.Forms.ProfessionalColors.CheckPressedBackground);
        }
        void ResetGripDark() {
            this.ResetColor("GripDark", System.Windows.Forms.ProfessionalColors.GripDark);
        }
        bool ShouldSerializeGripDark() {
            return this.ShouldSerializeColor("GripDark", System.Windows.Forms.ProfessionalColors.GripDark);
        }
        void ResetGripLight() {
            this.ResetColor("GripLight", System.Windows.Forms.ProfessionalColors.GripLight);
        }
        bool ShouldSerializeGripLight() {
            return this.ShouldSerializeColor("GripLight", System.Windows.Forms.ProfessionalColors.GripLight);
        }
        void ResetImageMarginGradientBegin() {
            this.ResetColor("ImageMarginGradientBegin", System.Windows.Forms.ProfessionalColors.ImageMarginGradientBegin);
        }
        bool ShouldSerializeImageMarginGradientBegin() {
            return this.ShouldSerializeColor("ImageMarginGradientBegin", System.Windows.Forms.ProfessionalColors.ImageMarginGradientBegin);
        }
        void ResetImageMarginGradientMiddle() {
            this.ResetColor("ImageMarginGradientMiddle", System.Windows.Forms.ProfessionalColors.ImageMarginGradientMiddle);
        }
        bool ShouldSerializeImageMarginGradientMiddle() {
            return this.ShouldSerializeColor("ImageMarginGradientMiddle", System.Windows.Forms.ProfessionalColors.ImageMarginGradientMiddle);
        }
        void ResetImageMarginGradientEnd() {
            this.ResetColor("ImageMarginGradientEnd", System.Windows.Forms.ProfessionalColors.ImageMarginGradientEnd);
        }
        bool ShouldSerializeImageMarginGradientEnd() {
            return this.ShouldSerializeColor("ImageMarginGradientEnd", System.Windows.Forms.ProfessionalColors.ImageMarginGradientEnd);
        }
        void ResetImageMarginRevealedGradientBegin() {
            this.ResetColor("ImageMarginRevealedGradientBegin", System.Windows.Forms.ProfessionalColors.ImageMarginRevealedGradientBegin);
        }
        bool ShouldSerializeImageMarginRevealedGradientBegin() {
            return this.ShouldSerializeColor("ImageMarginRevealedGradientBegin", System.Windows.Forms.ProfessionalColors.ImageMarginRevealedGradientBegin);
        }
        void ResetImageMarginRevealedGradientMiddle() {
            this.ResetColor("ImageMarginRevealedGradientMiddle", System.Windows.Forms.ProfessionalColors.ImageMarginRevealedGradientMiddle);
        }
        bool ShouldSerializeImageMarginRevealedGradientMiddle() {
            return this.ShouldSerializeColor("ImageMarginRevealedGradientMiddle", System.Windows.Forms.ProfessionalColors.ImageMarginRevealedGradientMiddle);
        }
        void ResetImageMarginRevealedGradientEnd() {
            this.ResetColor("ImageMarginRevealedGradientEnd", System.Windows.Forms.ProfessionalColors.ImageMarginRevealedGradientEnd);
        }
        bool ShouldSerializeImageMarginRevealedGradientEnd() {
            return this.ShouldSerializeColor("ImageMarginRevealedGradientEnd", System.Windows.Forms.ProfessionalColors.ImageMarginRevealedGradientEnd);
        }
        void ResetMenuStripGradientBegin() {
            this.ResetColor("MenuStripGradientBegin", System.Windows.Forms.ProfessionalColors.MenuStripGradientBegin);
        }
        bool ShouldSerializeMenuStripGradientBegin() {
            return this.ShouldSerializeColor("MenuStripGradientBegin", System.Windows.Forms.ProfessionalColors.MenuStripGradientBegin);
        }
        void ResetMenuStripGradientEnd() {
            this.ResetColor("MenuStripGradientEnd", System.Windows.Forms.ProfessionalColors.MenuStripGradientEnd);
        }
        bool ShouldSerializeMenuStripGradientEnd() {
            return this.ShouldSerializeColor("MenuStripGradientEnd", System.Windows.Forms.ProfessionalColors.MenuStripGradientEnd);
        }
        void ResetMenuItemSelected() {
            this.ResetColor("MenuItemSelected", System.Windows.Forms.ProfessionalColors.MenuItemSelected);
        }
        bool ShouldSerializeMenuItemSelected() {
            return this.ShouldSerializeColor("MenuItemSelected", System.Windows.Forms.ProfessionalColors.MenuItemSelected);
        }
        void ResetMenuItemBorder() {
            this.ResetColor("MenuItemBorder", System.Windows.Forms.ProfessionalColors.MenuItemBorder);
        }
        bool ShouldSerializeMenuItemBorder() {
            return this.ShouldSerializeColor("MenuItemBorder", System.Windows.Forms.ProfessionalColors.MenuItemBorder);
        }
        void ResetMenuBorder() {
            this.ResetColor("MenuBorder", System.Windows.Forms.ProfessionalColors.MenuBorder);
        }
        bool ShouldSerializeMenuBorder() {
            return this.ShouldSerializeColor("MenuBorder", System.Windows.Forms.ProfessionalColors.MenuBorder);
        }
        void ResetMenuItemSelectedGradientBegin() {
            this.ResetColor("MenuItemSelectedGradientBegin", System.Windows.Forms.ProfessionalColors.MenuItemSelectedGradientBegin);
        }
        bool ShouldSerializeMenuItemSelectedGradientBegin() {
            return this.ShouldSerializeColor("MenuItemSelectedGradientBegin", System.Windows.Forms.ProfessionalColors.MenuItemSelectedGradientBegin);
        }
        void ResetMenuItemSelectedGradientEnd() {
            this.ResetColor("MenuItemSelectedGradientEnd", System.Windows.Forms.ProfessionalColors.MenuItemSelectedGradientEnd);
        }
        bool ShouldSerializeMenuItemSelectedGradientEnd() {
            return this.ShouldSerializeColor("MenuItemSelectedGradientEnd", System.Windows.Forms.ProfessionalColors.MenuItemSelectedGradientEnd);
        }
        void ResetMenuItemPressedGradientBegin() {
            this.ResetColor("MenuItemPressedGradientBegin", System.Windows.Forms.ProfessionalColors.MenuItemPressedGradientBegin);
        }
        bool ShouldSerializeMenuItemPressedGradientBegin() {
            return this.ShouldSerializeColor("MenuItemPressedGradientBegin", System.Windows.Forms.ProfessionalColors.MenuItemPressedGradientBegin);
        }
        void ResetMenuItemPressedGradientMiddle() {
            this.ResetColor("MenuItemPressedGradientMiddle", System.Windows.Forms.ProfessionalColors.MenuItemPressedGradientMiddle);
        }
        bool ShouldSerializeMenuItemPressedGradientMiddle() {
            return this.ShouldSerializeColor("MenuItemPressedGradientMiddle", System.Windows.Forms.ProfessionalColors.MenuItemPressedGradientMiddle);
        }
        void ResetMenuItemPressedGradientEnd() {
            this.ResetColor("MenuItemPressedGradientEnd", System.Windows.Forms.ProfessionalColors.MenuItemPressedGradientEnd);
        }
        bool ShouldSerializeMenuItemPressedGradientEnd() {
            return this.ShouldSerializeColor("MenuItemPressedGradientEnd", System.Windows.Forms.ProfessionalColors.MenuItemPressedGradientEnd);
        }
        void ResetRaftingContainerGradientBegin() {
            this.ResetColor("RaftingContainerGradientBegin", System.Windows.Forms.ProfessionalColors.RaftingContainerGradientBegin);
        }
        bool ShouldSerializeRaftingContainerGradientBegin() {
            return this.ShouldSerializeColor("RaftingContainerGradientBegin", System.Windows.Forms.ProfessionalColors.RaftingContainerGradientBegin);
        }
        void ResetRaftingContainerGradientEnd() {
            this.ResetColor("RaftingContainerGradientEnd", System.Windows.Forms.ProfessionalColors.RaftingContainerGradientEnd);
        }
        bool ShouldSerializeRaftingContainerGradientEnd() {
            return this.ShouldSerializeColor("RaftingContainerGradientEnd", System.Windows.Forms.ProfessionalColors.RaftingContainerGradientEnd);
        }
        void ResetSeparatorDark() {
            this.ResetColor("SeparatorDark", System.Windows.Forms.ProfessionalColors.SeparatorDark);
        }
        bool ShouldSerializeSeparatorDark() {
            return this.ShouldSerializeColor("SeparatorDark", System.Windows.Forms.ProfessionalColors.SeparatorDark);
        }
        void ResetSeparatorLight() {
            this.ResetColor("SeparatorLight", System.Windows.Forms.ProfessionalColors.SeparatorLight);
        }
        bool ShouldSerializeSeparatorLight() {
            return this.ShouldSerializeColor("SeparatorLight", System.Windows.Forms.ProfessionalColors.SeparatorLight);
        }
        void ResetStatusStripGradientBegin() {
            this.ResetColor("StatusStripGradientBegin", System.Windows.Forms.ProfessionalColors.StatusStripGradientBegin);
        }
        bool ShouldSerializeStatusStripGradientBegin() {
            return this.ShouldSerializeColor("StatusStripGradientBegin", System.Windows.Forms.ProfessionalColors.StatusStripGradientBegin);
        }
        void ResetStatusStripGradientEnd() {
            this.ResetColor("StatusStripGradientEnd", System.Windows.Forms.ProfessionalColors.StatusStripGradientEnd);
        }
        bool ShouldSerializeStatusStripGradientEnd() {
            return this.ShouldSerializeColor("StatusStripGradientEnd", System.Windows.Forms.ProfessionalColors.StatusStripGradientEnd);
        }
        void ResetToolStripBorder() {
            this.ResetColor("ToolStripBorder", System.Windows.Forms.ProfessionalColors.ToolStripBorder);
        }
        bool ShouldSerializeToolStripBorder() {
            return this.ShouldSerializeColor("ToolStripBorder", System.Windows.Forms.ProfessionalColors.ToolStripBorder);
        }
        void ResetToolStripDropDownBackground() {
            this.ResetColor("ToolStripDropDownBackground", System.Windows.Forms.ProfessionalColors.ToolStripDropDownBackground);
        }
        bool ShouldSerializeToolStripDropDownBackground() {
            return this.ShouldSerializeColor("ToolStripDropDownBackground", System.Windows.Forms.ProfessionalColors.ToolStripDropDownBackground);
        }
        void ResetToolStripGradientBegin() {
            this.ResetColor("ToolStripGradientBegin", System.Windows.Forms.ProfessionalColors.ToolStripGradientBegin);
        }
        bool ShouldSerializeToolStripGradientBegin() {
            return this.ShouldSerializeColor("ToolStripGradientBegin", System.Windows.Forms.ProfessionalColors.ToolStripGradientBegin);
        }
        void ResetToolStripGradientMiddle() {
            this.ResetColor("ToolStripGradientMiddle", System.Windows.Forms.ProfessionalColors.ToolStripGradientMiddle);
        }
        bool ShouldSerializeToolStripGradientMiddle() {
            return this.ShouldSerializeColor("ToolStripGradientMiddle", System.Windows.Forms.ProfessionalColors.ToolStripGradientMiddle);
        }
        void ResetToolStripGradientEnd() {
            this.ResetColor("ToolStripGradientEnd", System.Windows.Forms.ProfessionalColors.ToolStripGradientEnd);
        }
        bool ShouldSerializeToolStripGradientEnd() {
            return this.ShouldSerializeColor("ToolStripGradientEnd", System.Windows.Forms.ProfessionalColors.ToolStripGradientEnd);
        }
        void ResetToolStripContentPanelGradientBegin() {
            this.ResetColor("ToolStripContentPanelGradientBegin", System.Windows.Forms.ProfessionalColors.ToolStripContentPanelGradientBegin);
        }
        bool ShouldSerializeToolStripContentPanelGradientBegin() {
            return this.ShouldSerializeColor("ToolStripContentPanelGradientBegin", System.Windows.Forms.ProfessionalColors.ToolStripContentPanelGradientBegin);
        }
        void ResetToolStripContentPanelGradientEnd() {
            this.ResetColor("ToolStripContentPanelGradientEnd", System.Windows.Forms.ProfessionalColors.ToolStripContentPanelGradientEnd);
        }
        bool ShouldSerializeToolStripContentPanelGradientEnd() {
            return this.ShouldSerializeColor("ToolStripContentPanelGradientEnd", System.Windows.Forms.ProfessionalColors.ToolStripContentPanelGradientEnd);
        }
        void ResetToolStripPanelGradientBegin() {
            this.ResetColor("ToolStripPanelGradientBegin", System.Windows.Forms.ProfessionalColors.ToolStripPanelGradientBegin);
        }
        bool ShouldSerializeToolStripPanelGradientBegin() {
            return this.ShouldSerializeColor("ToolStripPanelGradientBegin", System.Windows.Forms.ProfessionalColors.ToolStripPanelGradientBegin);
        }
        void ResetToolStripPanelGradientEnd() {
            this.ResetColor("ToolStripPanelGradientEnd", System.Windows.Forms.ProfessionalColors.ToolStripPanelGradientEnd);
        }
        bool ShouldSerializeToolStripPanelGradientEnd() {
            return this.ShouldSerializeColor("ToolStripPanelGradientEnd", System.Windows.Forms.ProfessionalColors.ToolStripPanelGradientEnd);
        }
        void ResetOverflowButtonGradientBegin() {
            this.ResetColor("OverflowButtonGradientBegin", System.Windows.Forms.ProfessionalColors.OverflowButtonGradientBegin);
        }
        bool ShouldSerializeOverflowButtonGradientBegin() {
            return this.ShouldSerializeColor("OverflowButtonGradientBegin", System.Windows.Forms.ProfessionalColors.OverflowButtonGradientBegin);
        }
        void ResetOverflowButtonGradientMiddle() {
            this.ResetColor("OverflowButtonGradientMiddle", System.Windows.Forms.ProfessionalColors.OverflowButtonGradientMiddle);
        }
        bool ShouldSerializeOverflowButtonGradientMiddle() {
            return this.ShouldSerializeColor("OverflowButtonGradientMiddle", System.Windows.Forms.ProfessionalColors.OverflowButtonGradientMiddle);
        }
        void ResetOverflowButtonGradientEnd() {
            this.ResetColor("OverflowButtonGradientEnd", System.Windows.Forms.ProfessionalColors.OverflowButtonGradientEnd);
        }
        bool ShouldSerializeOverflowButtonGradientEnd() {
            return this.ShouldSerializeColor("OverflowButtonGradientEnd", System.Windows.Forms.ProfessionalColors.OverflowButtonGradientEnd);
        }
        void ResetButtonCheckedText() {
            this.ResetColor("ButtonCheckedText", System.Drawing.SystemColors.ControlText);
        }
        bool ShouldSerializeButtonCheckedText() {
            return this.ShouldSerializeColor("ButtonCheckedText", System.Drawing.SystemColors.ControlText);
        }
        void ResetButtonPressedText() {
            this.ResetColor("ButtonPressedText", System.Drawing.SystemColors.ControlText);
        }
        bool ShouldSerializeButtonPressedText() {
            return this.ShouldSerializeColor("ButtonPressedText", System.Drawing.SystemColors.ControlText);
        }
        void ResetButtonSelectedText() {
            this.ResetColor("ButtonSelectedText", System.Drawing.SystemColors.ControlText);
        }
        bool ShouldSerializeButtonSelectedText() {
            return this.ShouldSerializeColor("ButtonSelectedText", System.Drawing.SystemColors.ControlText);
        }
        void ResetMenuItemText() {
            this.ResetColor("MenuItemText", System.Drawing.SystemColors.MenuText);
        }
        bool ShouldSerializeMenuItemText() {
            return this.ShouldSerializeColor("MenuItemText", System.Drawing.SystemColors.MenuText);
        }
        void ResetToolStripDropDownText() {
            this.ResetColor("ToolStripDropDownText", System.Drawing.SystemColors.MenuText);
        }
        bool ShouldSerializeToolStripDropDownText() {
            return this.ShouldSerializeColor("ToolStripDropDownText", System.Drawing.SystemColors.MenuText);
        }
        void ResetMenuItemPressedText() {
            this.ResetColor("MenuItemPressedText", System.Drawing.SystemColors.HighlightText);
        }
        bool ShouldSerializeMenuItemPressedText() {
            return this.ShouldSerializeColor("MenuItemPressedText", System.Drawing.SystemColors.HighlightText);
        }
        void ResetMenuItemSelectedText() {
            this.ResetColor("MenuItemSelectedText", System.Drawing.SystemColors.HighlightText);
        }
        bool ShouldSerializeMenuItemSelectedText() {
            return this.ShouldSerializeColor("MenuItemSelectedText", System.Drawing.SystemColors.HighlightText);
        }
        void ResetStatusStripText() {
            this.ResetColor("StatusStripText", System.Drawing.SystemColors.ControlText);
        }
        bool ShouldSerializeStatusStripText() {
            return this.ShouldSerializeColor("StatusStripText", System.Drawing.SystemColors.ControlText);
        }
    }
    public partial class CustomProfessionalColorTable : ProfessionalColorTable {
        public override System.Drawing.Color ButtonSelectedHighlight {
            get {
                return this.professionalColors.ButtonSelectedHighlight;
            }
        }
        public override System.Drawing.Color ButtonSelectedHighlightBorder {
            get {
                return this.professionalColors.ButtonSelectedHighlightBorder;
            }
        }
        public override System.Drawing.Color ButtonPressedHighlight {
            get {
                return this.professionalColors.ButtonPressedHighlight;
            }
        }
        public override System.Drawing.Color ButtonPressedHighlightBorder {
            get {
                return this.professionalColors.ButtonPressedHighlightBorder;
            }
        }
        public override System.Drawing.Color ButtonCheckedHighlight {
            get {
                return this.professionalColors.ButtonCheckedHighlight;
            }
        }
        public override System.Drawing.Color ButtonCheckedHighlightBorder {
            get {
                return this.professionalColors.ButtonCheckedHighlightBorder;
            }
        }
        public override System.Drawing.Color ButtonPressedBorder {
            get {
                return this.professionalColors.ButtonPressedBorder;
            }
        }
        public override System.Drawing.Color ButtonSelectedBorder {
            get {
                return this.professionalColors.ButtonSelectedBorder;
            }
        }
        public override System.Drawing.Color ButtonCheckedGradientBegin {
            get {
                return this.professionalColors.ButtonCheckedGradientBegin;
            }
        }
        public override System.Drawing.Color ButtonCheckedGradientMiddle {
            get {
                return this.professionalColors.ButtonCheckedGradientMiddle;
            }
        }
        public override System.Drawing.Color ButtonCheckedGradientEnd {
            get {
                return this.professionalColors.ButtonCheckedGradientEnd;
            }
        }
        public override System.Drawing.Color ButtonSelectedGradientBegin {
            get {
                return this.professionalColors.ButtonSelectedGradientBegin;
            }
        }
        public override System.Drawing.Color ButtonSelectedGradientMiddle {
            get {
                return this.professionalColors.ButtonSelectedGradientMiddle;
            }
        }
        public override System.Drawing.Color ButtonSelectedGradientEnd {
            get {
                return this.professionalColors.ButtonSelectedGradientEnd;
            }
        }
        public override System.Drawing.Color ButtonPressedGradientBegin {
            get {
                return this.professionalColors.ButtonPressedGradientBegin;
            }
        }
        public override System.Drawing.Color ButtonPressedGradientMiddle {
            get {
                return this.professionalColors.ButtonPressedGradientMiddle;
            }
        }
        public override System.Drawing.Color ButtonPressedGradientEnd {
            get {
                return this.professionalColors.ButtonPressedGradientEnd;
            }
        }
        public override System.Drawing.Color CheckBackground {
            get {
                return this.professionalColors.CheckBackground;
            }
        }
        public override System.Drawing.Color CheckSelectedBackground {
            get {
                return this.professionalColors.CheckSelectedBackground;
            }
        }
        public override System.Drawing.Color CheckPressedBackground {
            get {
                return this.professionalColors.CheckPressedBackground;
            }
        }
        public override System.Drawing.Color GripDark {
            get {
                return this.professionalColors.GripDark;
            }
        }
        public override System.Drawing.Color GripLight {
            get {
                return this.professionalColors.GripLight;
            }
        }
        public override System.Drawing.Color ImageMarginGradientBegin {
            get {
                return this.professionalColors.ImageMarginGradientBegin;
            }
        }
        public override System.Drawing.Color ImageMarginGradientMiddle {
            get {
                return this.professionalColors.ImageMarginGradientMiddle;
            }
        }
        public override System.Drawing.Color ImageMarginGradientEnd {
            get {
                return this.professionalColors.ImageMarginGradientEnd;
            }
        }
        public override System.Drawing.Color ImageMarginRevealedGradientBegin {
            get {
                return this.professionalColors.ImageMarginRevealedGradientBegin;
            }
        }
        public override System.Drawing.Color ImageMarginRevealedGradientMiddle {
            get {
                return this.professionalColors.ImageMarginRevealedGradientMiddle;
            }
        }
        public override System.Drawing.Color ImageMarginRevealedGradientEnd {
            get {
                return this.professionalColors.ImageMarginRevealedGradientEnd;
            }
        }
        public override System.Drawing.Color MenuStripGradientBegin {
            get {
                return this.professionalColors.MenuStripGradientBegin;
            }
        }
        public override System.Drawing.Color MenuStripGradientEnd {
            get {
                return this.professionalColors.MenuStripGradientEnd;
            }
        }
        public override System.Drawing.Color MenuItemSelected {
            get {
                return this.professionalColors.MenuItemSelected;
            }
        }
        public override System.Drawing.Color MenuItemBorder {
            get {
                return this.professionalColors.MenuItemBorder;
            }
        }
        public override System.Drawing.Color MenuBorder {
            get {
                return this.professionalColors.MenuBorder;
            }
        }
        public override System.Drawing.Color MenuItemSelectedGradientBegin {
            get {
                return this.professionalColors.MenuItemSelectedGradientBegin;
            }
        }
        public override System.Drawing.Color MenuItemSelectedGradientEnd {
            get {
                return this.professionalColors.MenuItemSelectedGradientEnd;
            }
        }
        public override System.Drawing.Color MenuItemPressedGradientBegin {
            get {
                return this.professionalColors.MenuItemPressedGradientBegin;
            }
        }
        public override System.Drawing.Color MenuItemPressedGradientMiddle {
            get {
                return this.professionalColors.MenuItemPressedGradientMiddle;
            }
        }
        public override System.Drawing.Color MenuItemPressedGradientEnd {
            get {
                return this.professionalColors.MenuItemPressedGradientEnd;
            }
        }
        public override System.Drawing.Color RaftingContainerGradientBegin {
            get {
                return this.professionalColors.RaftingContainerGradientBegin;
            }
        }
        public override System.Drawing.Color RaftingContainerGradientEnd {
            get {
                return this.professionalColors.RaftingContainerGradientEnd;
            }
        }
        public override System.Drawing.Color SeparatorDark {
            get {
                return this.professionalColors.SeparatorDark;
            }
        }
        public override System.Drawing.Color SeparatorLight {
            get {
                return this.professionalColors.SeparatorLight;
            }
        }
        public override System.Drawing.Color StatusStripGradientBegin {
            get {
                return this.professionalColors.StatusStripGradientBegin;
            }
        }
        public override System.Drawing.Color StatusStripGradientEnd {
            get {
                return this.professionalColors.StatusStripGradientEnd;
            }
        }
        public override System.Drawing.Color ToolStripBorder {
            get {
                return this.professionalColors.ToolStripBorder;
            }
        }
        public override System.Drawing.Color ToolStripDropDownBackground {
            get {
                return this.professionalColors.ToolStripDropDownBackground;
            }
        }
        public override System.Drawing.Color ToolStripGradientBegin {
            get {
                return this.professionalColors.ToolStripGradientBegin;
            }
        }
        public override System.Drawing.Color ToolStripGradientMiddle {
            get {
                return this.professionalColors.ToolStripGradientMiddle;
            }
        }
        public override System.Drawing.Color ToolStripGradientEnd {
            get {
                return this.professionalColors.ToolStripGradientEnd;
            }
        }
        public override System.Drawing.Color ToolStripContentPanelGradientBegin {
            get {
                return this.professionalColors.ToolStripContentPanelGradientBegin;
            }
        }
        public override System.Drawing.Color ToolStripContentPanelGradientEnd {
            get {
                return this.professionalColors.ToolStripContentPanelGradientEnd;
            }
        }
        public override System.Drawing.Color ToolStripPanelGradientBegin {
            get {
                return this.professionalColors.ToolStripPanelGradientBegin;
            }
        }
        public override System.Drawing.Color ToolStripPanelGradientEnd {
            get {
                return this.professionalColors.ToolStripPanelGradientEnd;
            }
        }
        public override System.Drawing.Color OverflowButtonGradientBegin {
            get {
                return this.professionalColors.OverflowButtonGradientBegin;
            }
        }
        public override System.Drawing.Color OverflowButtonGradientMiddle {
            get {
                return this.professionalColors.OverflowButtonGradientMiddle;
            }
        }
        public override System.Drawing.Color OverflowButtonGradientEnd {
            get {
                return this.professionalColors.OverflowButtonGradientEnd;
            }
        }
    }
}
