//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WmcSoft.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WmcSoft.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key &apos;{0}&apos; is missing from the appSettings section..
        /// </summary>
        internal static string AppSettingsCheckpointKeyIsMissingError {
            get {
                return ResourceManager.GetString("AppSettingsCheckpointKeyIsMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument can not have an empty value..
        /// </summary>
        internal static string ArgumentEmpty {
            get {
                return ResourceManager.GetString("ArgumentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument cannot be a null or empty string..
        /// </summary>
        internal static string ArgumentNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not assignable to type {1}..
        /// </summary>
        internal static string CantAssignTo {
            get {
                return ResourceManager.GetString("CantAssignTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load assembly {0}. Verify if the type {1} syntax is correct..
        /// </summary>
        internal static string CantLoadAssembly {
            get {
                return ResourceManager.GetString("CantLoadAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load type {0}..
        /// </summary>
        internal static string CantLoadType {
            get {
                return ResourceManager.GetString("CantLoadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component {0} must be sited in a container in order to function properly..
        /// </summary>
        internal static string ComponentNotSited {
            get {
                return ResourceManager.GetString("ComponentNotSited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component can not be null..
        /// </summary>
        internal static string ComponentNull {
            get {
                return ResourceManager.GetString("ComponentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load the configuration section &apos;{0}&apos;..
        /// </summary>
        internal static string ConfigurationCheckpointCannotLoadSection {
            get {
                return ResourceManager.GetString("ConfigurationCheckpointCannotLoadSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dispatcher does not support cancellation..
        /// </summary>
        internal static string DispatcherDoesntSuppportCancellation {
            get {
                return ResourceManager.GetString("DispatcherDoesntSuppportCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid assembly name {0}..
        /// </summary>
        internal static string InvalidAssemblyName {
            get {
                return ResourceManager.GetString("InvalidAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string InvalidFormatMessage {
            get {
                return ResourceManager.GetString("InvalidFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid qualified type name {0}..
        /// </summary>
        internal static string InvalidQualifiedName {
            get {
                return ResourceManager.GetString("InvalidQualifiedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service instance of type {0} is not assignable to service type {1}..
        /// </summary>
        internal static string InvalidServiceInstance {
            get {
                return ResourceManager.GetString("InvalidServiceInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0}, required for component {1} is not available in the current container..
        /// </summary>
        internal static string MissingServiceForComponentMessage {
            get {
                return ResourceManager.GetString("MissingServiceForComponentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required service {0} is missing..
        /// </summary>
        internal static string MissingServiceMessage {
            get {
                return ResourceManager.GetString("MissingServiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service provider to look for dependencies can not be null..
        /// </summary>
        internal static string ProviderNull {
            get {
                return ResourceManager.GetString("ProviderNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} already exists in the container..
        /// </summary>
        internal static string ServiceExists {
            get {
                return ResourceManager.GetString("ServiceExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized attribute &apos;{0}&apos;..
        /// </summary>
        internal static string UnrecognizedAttributeFormat {
            get {
                return ResourceManager.GetString("UnrecognizedAttributeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized element &apos;{0}&apos;..
        /// </summary>
        internal static string UnrecognizedElementFormat {
            get {
                return ResourceManager.GetString("UnrecognizedElementFormat", resourceCulture);
            }
        }
    }
}
