//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WmcSoft.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WmcSoft.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The key &apos;{0}&apos; is missing from the appSettings section..
        /// </summary>
        internal static string AppSettingsCheckpointKeyIsMissingError {
            get {
                return ResourceManager.GetString("AppSettingsCheckpointKeyIsMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Argument can not have an empty value..
        /// </summary>
        internal static string ArgumentEmpty {
            get {
                return ResourceManager.GetString("ArgumentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The argument cannot be a null or empty string..
        /// </summary>
        internal static string ArgumentNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type {0} is not assignable to type {1}..
        /// </summary>
        internal static string CantAssignTo {
            get {
                return ResourceManager.GetString("CantAssignTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not load assembly {0}. Verify if the type {1} syntax is correct..
        /// </summary>
        internal static string CantLoadAssembly {
            get {
                return ResourceManager.GetString("CantLoadAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not load type {0}..
        /// </summary>
        internal static string CantLoadType {
            get {
                return ResourceManager.GetString("CantLoadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect type. Expecting {0} but received {1}.&quot;.
        /// </summary>
        internal static string ComparisonIncorrectTypeFormat {
            get {
                return ResourceManager.GetString("ComparisonIncorrectTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Component {0} must be sited in a container in order to function properly..
        /// </summary>
        internal static string ComponentNotSited {
            get {
                return ResourceManager.GetString("ComponentNotSited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The component can not be null..
        /// </summary>
        internal static string ComponentNull {
            get {
                return ResourceManager.GetString("ComponentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot load the configuration section &apos;{0}&apos;..
        /// </summary>
        internal static string ConfigurationCheckpointCannotLoadSection {
            get {
                return ResourceManager.GetString("ConfigurationCheckpointCannotLoadSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The dispatcher does not support cancellation..
        /// </summary>
        internal static string DispatcherDoesntSuppportCancellation {
            get {
                return ResourceManager.GetString("DispatcherDoesntSuppportCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid assembly name {0}..
        /// </summary>
        internal static string InvalidAssemblyName {
            get {
                return ResourceManager.GetString("InvalidAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The format of &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string InvalidFormatMessage {
            get {
                return ResourceManager.GetString("InvalidFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} threw &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidOperationExceptionRethrow {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionRethrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid qualified type name {0}..
        /// </summary>
        internal static string InvalidQualifiedName {
            get {
                return ResourceManager.GetString("InvalidQualifiedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service instance of type {0} is not assignable to service type {1}..
        /// </summary>
        internal static string InvalidServiceInstance {
            get {
                return ResourceManager.GetString("InvalidServiceInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service {0}, required for component {1} is not available in the current container..
        /// </summary>
        internal static string MissingServiceForComponentMessage {
            get {
                return ResourceManager.GetString("MissingServiceForComponentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The required service {0} is missing..
        /// </summary>
        internal static string MissingServiceMessage {
            get {
                return ResourceManager.GetString("MissingServiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The service provider to look for dependencies can not be null..
        /// </summary>
        internal static string ProviderNull {
            get {
                return ResourceManager.GetString("ProviderNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service {0} already exists in the container..
        /// </summary>
        internal static string ServiceExists {
            get {
                return ResourceManager.GetString("ServiceExists", resourceCulture);
            }
        }
    }
}
