//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WmcSoft.Units.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WmcSoft.Units.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conversion from &quot;{0}&quot; to &quot;{1}&quot; already exists..
        /// </summary>
        internal static string DuplicateConversionException {
            get {
                return ResourceManager.GetString("DuplicateConversionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scale factor must not be 1..
        /// </summary>
        internal static string EquivalentUnitException {
            get {
                return ResourceManager.GetString("EquivalentUnitException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both Quantity objets must be in the same Metric..
        /// </summary>
        internal static string IncompatibleMetricException {
            get {
                return ResourceManager.GetString("IncompatibleMetricException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scale factor must be strictly positive..
        /// </summary>
        internal static string InvalidScaleFactorException {
            get {
                return ResourceManager.GetString("InvalidScaleFactorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target of the first conversion &quot;{0}&quot; must match the source of the second &quot;{1}&quot;..
        /// </summary>
        internal static string InvalidUnitConversionPath {
            get {
                return ResourceManager.GetString("InvalidUnitConversionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Metric of the quantity is not a Unit..
        /// </summary>
        internal static string NotAUnitException {
            get {
                return ResourceManager.GetString("NotAUnitException", resourceCulture);
            }
        }
    }
}
