//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WmcSoft.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WmcSoft.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abort.
        /// </summary>
        internal static string AbortButton {
            get {
                return ResourceManager.GetString("AbortButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add TabStrip page.
        /// </summary>
        internal static string AddTab {
            get {
                return ResourceManager.GetString("AddTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commands.
        /// </summary>
        internal static string CommandManagerEventsTabName {
            get {
                return ResourceManager.GetString("CommandManagerEventsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continue.
        /// </summary>
        internal static string ContinueButton {
            get {
                return ResourceManager.GetString("ContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à , .
        /// </summary>
        internal static string DaysOfWeekSeparator {
            get {
                return ResourceManager.GetString("DaysOfWeekSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Error48 {
            get {
                object obj = ResourceManager.GetObject("Error48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unhandled exception has occurred in a component in your application.
        ///If you click Continue, the application will ignore this error and attempt to continue.
        ///
        ///{0}..
        /// </summary>
        internal static string ExceptionFormContinueErrorMessage {
            get {
                return ResourceManager.GetString("ExceptionFormContinueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unhandled exception has occurred in your application.
        ///If you click Continue, the application will ignore this error and attempt to continue.
        ///If you click Quit, the application will close immediately.
        ///
        ///{0}..
        /// </summary>
        internal static string ExceptionFormErrorMessage {
            get {
                return ResourceManager.GetString("ExceptionFormErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exception Text.
        /// </summary>
        internal static string ExceptionFormExceptionSection {
            get {
                return ResourceManager.GetString("ExceptionFormExceptionSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}
        ///    Assembly Version: {1}
        ///    Win32 Version: {2}
        ///    CodeBase: {3}
        ///.
        /// </summary>
        internal static string ExceptionFormMessageAssembliesEntry {
            get {
                return ResourceManager.GetString("ExceptionFormMessageAssembliesEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loaded Assemblies.
        /// </summary>
        internal static string ExceptionFormMessageLoadedAssembliesSection {
            get {
                return ResourceManager.GetString("ExceptionFormMessageLoadedAssembliesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///************** {0} **************
        ///.
        /// </summary>
        internal static string ExceptionFormMessageSectionSeparator {
            get {
                return ResourceManager.GetString("ExceptionFormMessageSectionSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ----------------------------------------
        ///.
        /// </summary>
        internal static string ExceptionFormMessageSeparator {
            get {
                return ResourceManager.GetString("ExceptionFormMessageSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application attempted to perform an operation not allowed by the security policy. To grant this application the required permission, contact your system administrator, or use the Microsoft .NET Framework Configuration tool.
        ///
        ///If you click Continue, the application will ignore this error and attempt to continue.
        ///
        ///{1}..
        /// </summary>
        internal static string ExceptionFormSecurityContinueErrorMessage {
            get {
                return ResourceManager.GetString("ExceptionFormSecurityContinueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application attempted to perform an operation not allowed by the security policy. To grant this application the required permission, contact your system administrator, or use the Microsoft .NET Framework Configuration tool.
        ///
        ///If you click Continue, the application will ignore this error and attempt to continue.
        ///If you click Quit, the application will close immediately.
        ///
        ///{1}..
        /// </summary>
        internal static string ExceptionFormSecurityErrorMessage {
            get {
                return ResourceManager.GetString("ExceptionFormSecurityErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}..
        /// </summary>
        internal static string ExceptionFormWarningMessage {
            get {
                return ResourceManager.GetString("ExceptionFormWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help.
        /// </summary>
        internal static string HelpButton {
            get {
                return ResourceManager.GetString("HelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ignore.
        /// </summary>
        internal static string IgnoreButton {
            get {
                return ResourceManager.GetString("IgnoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Info48 {
            get {
                object obj = ResourceManager.GetObject("Info48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information.
        /// </summary>
        internal static string InformationCaption {
            get {
                return ResourceManager.GetString("InformationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The name &quot;{0}&quot; is not a valid identifier..
        /// </summary>
        internal static string InvalidNameArgumentException {
            get {
                return ResourceManager.GetString("InvalidNameArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LightBulb48 {
            get {
                object obj = ResourceManager.GetObject("LightBulb48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Online.
        /// </summary>
        internal static string NetworkAvailableText {
            get {
                return ResourceManager.GetString("NetworkAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The network is currently available..
        /// </summary>
        internal static string NetworkAvailableToolTip {
            get {
                return ResourceManager.GetString("NetworkAvailableToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Offline.
        /// </summary>
        internal static string NetworkNotAvailableText {
            get {
                return ResourceManager.GetString("NetworkNotAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The network is currently not available..
        /// </summary>
        internal static string NetworkNotAvailableToolTip {
            get {
                return ResourceManager.GetString("NetworkNotAvailableToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        internal static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap None48 {
            get {
                object obj = ResourceManager.GetObject("None48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N/A.
        /// </summary>
        internal static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There are no zones in the workspace to display smart parts..
        /// </summary>
        internal static string NoZonesInZoneWorkspace {
            get {
                return ResourceManager.GetString("NoZonesInZoneWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is no zone named {0} to display the smart part in..
        /// </summary>
        internal static string NoZoneWithName {
            get {
                return ResourceManager.GetString("NoZoneWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        internal static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Question48 {
            get {
                object obj = ResourceManager.GetObject("Question48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Question.
        /// </summary>
        internal static string QuestionCaption {
            get {
                return ResourceManager.GetString("QuestionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit.
        /// </summary>
        internal static string QuitButton {
            get {
                return ResourceManager.GetString("QuitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à day.
        /// </summary>
        internal static string RecurrenceDailyEveryDay {
            get {
                return ResourceManager.GetString("RecurrenceDailyEveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} days.
        /// </summary>
        internal static string RecurrenceDailyEveryNthDays {
            get {
                return ResourceManager.GetString("RecurrenceDailyEveryNthDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à weekday.
        /// </summary>
        internal static string RecurrenceDailyEveryWeekDays {
            get {
                return ResourceManager.GetString("RecurrenceDailyEveryWeekDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à weekend day.
        /// </summary>
        internal static string RecurrenceDailyEveryWeekendDays {
            get {
                return ResourceManager.GetString("RecurrenceDailyEveryWeekendDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Occurs every {0} effective {1} from {2} to {3}.
        /// </summary>
        internal static string RecurrenceFormat {
            get {
                return ResourceManager.GetString("RecurrenceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à day {0} of every month.
        /// </summary>
        internal static string RecurrenceMonthlyEveryMonth {
            get {
                return ResourceManager.GetString("RecurrenceMonthlyEveryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à day {0} of every {1} months.
        /// </summary>
        internal static string RecurrenceMonthlyEveryNthMonths {
            get {
                return ResourceManager.GetString("RecurrenceMonthlyEveryNthMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} {1} of every month.
        /// </summary>
        internal static string RecurrenceMonthNthEveryMonth {
            get {
                return ResourceManager.GetString("RecurrenceMonthNthEveryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} {1} of every {2} months.
        /// </summary>
        internal static string RecurrenceMonthNthEveryNthMonths {
            get {
                return ResourceManager.GetString("RecurrenceMonthNthEveryNthMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {1} on {0}.
        /// </summary>
        internal static string RecurrenceWeeklyEveryNthWeek {
            get {
                return ResourceManager.GetString("RecurrenceWeeklyEveryNthWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}.
        /// </summary>
        internal static string RecurrenceWeeklyEveryWeek {
            get {
                return ResourceManager.GetString("RecurrenceWeeklyEveryWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} {1}.
        /// </summary>
        internal static string RecurrenceYearly {
            get {
                return ResourceManager.GetString("RecurrenceYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} {1} of {2}.
        /// </summary>
        internal static string RecurrenceYearNth {
            get {
                return ResourceManager.GetString("RecurrenceYearNth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retry.
        /// </summary>
        internal static string RetryButton {
            get {
                return ResourceManager.GetString("RetryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Smart part is not a control..
        /// </summary>
        internal static string SmartPartNotControl {
            get {
                return ResourceManager.GetString("SmartPartNotControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Smart part has not been shown previously by the current manager..
        /// </summary>
        internal static string SmartPartNotInManager {
            get {
                return ResourceManager.GetString("SmartPartNotInManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sunday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Did You Know....
        /// </summary>
        internal static string TipOfTheDayFormDefaultTitle {
            get {
                return ResourceManager.GetString("TipOfTheDayFormDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Workspace supports smart parts of type {0}..
        /// </summary>
        internal static string UnsupportedSmartPartType {
            get {
                return ResourceManager.GetString("UnsupportedSmartPartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Warning48 {
            get {
                object obj = ResourceManager.GetObject("Warning48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning.
        /// </summary>
        internal static string WarningCaption {
            get {
                return ResourceManager.GetString("WarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        internal static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
    }
}
