//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WmcSoft.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WmcSoft.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string AbortButton {
            get {
                return ResourceManager.GetString("AbortButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add TabStrip page.
        /// </summary>
        internal static string AddTab {
            get {
                return ResourceManager.GetString("AddTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string CommandManagerEventsTabName {
            get {
                return ResourceManager.GetString("CommandManagerEventsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string ContinueButton {
            get {
                return ResourceManager.GetString("ContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string DaysOfWeekSeparator {
            get {
                return ResourceManager.GetString("DaysOfWeekSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Error48 {
            get {
                object obj = ResourceManager.GetObject("Error48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception has occurred in a component in your application.
        ///If you click Continue, the application will ignore this error and attempt to continue.
        ///
        ///{0}..
        /// </summary>
        internal static string ExceptionFormContinueErrorMessage {
            get {
                return ResourceManager.GetString("ExceptionFormContinueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception has occurred in your application.
        ///If you click Continue, the application will ignore this error and attempt to continue.
        ///If you click Quit, the application will close immediately.
        ///
        ///{0}..
        /// </summary>
        internal static string ExceptionFormErrorMessage {
            get {
                return ResourceManager.GetString("ExceptionFormErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Text.
        /// </summary>
        internal static string ExceptionFormExceptionSection {
            get {
                return ResourceManager.GetString("ExceptionFormExceptionSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///    Assembly Version: {1}
        ///    Win32 Version: {2}
        ///    CodeBase: {3}
        ///.
        /// </summary>
        internal static string ExceptionFormMessageAssembliesEntry {
            get {
                return ResourceManager.GetString("ExceptionFormMessageAssembliesEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded Assemblies.
        /// </summary>
        internal static string ExceptionFormMessageLoadedAssembliesSection {
            get {
                return ResourceManager.GetString("ExceptionFormMessageLoadedAssembliesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///************** {0} **************
        ///.
        /// </summary>
        internal static string ExceptionFormMessageSectionSeparator {
            get {
                return ResourceManager.GetString("ExceptionFormMessageSectionSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------------
        ///.
        /// </summary>
        internal static string ExceptionFormMessageSeparator {
            get {
                return ResourceManager.GetString("ExceptionFormMessageSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application attempted to perform an operation not allowed by the security policy. To grant this application the required permission, contact your system administrator, or use the Microsoft .NET Framework Configuration tool.
        ///
        ///If you click Continue, the application will ignore this error and attempt to continue.
        ///
        ///{1}..
        /// </summary>
        internal static string ExceptionFormSecurityContinueErrorMessage {
            get {
                return ResourceManager.GetString("ExceptionFormSecurityContinueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application attempted to perform an operation not allowed by the security policy. To grant this application the required permission, contact your system administrator, or use the Microsoft .NET Framework Configuration tool.
        ///
        ///If you click Continue, the application will ignore this error and attempt to continue.
        ///If you click Quit, the application will close immediately.
        ///
        ///{1}..
        /// </summary>
        internal static string ExceptionFormSecurityErrorMessage {
            get {
                return ResourceManager.GetString("ExceptionFormSecurityErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}..
        /// </summary>
        internal static string ExceptionFormWarningMessage {
            get {
                return ResourceManager.GetString("ExceptionFormWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpButton {
            get {
                return ResourceManager.GetString("HelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string IgnoreButton {
            get {
                return ResourceManager.GetString("IgnoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Info48 {
            get {
                object obj = ResourceManager.GetObject("Info48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string InformationCaption {
            get {
                return ResourceManager.GetString("InformationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &quot;{0}&quot; is not a valid identifier..
        /// </summary>
        internal static string InvalidNameArgumentException {
            get {
                return ResourceManager.GetString("InvalidNameArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LightBulb48 {
            get {
                object obj = ResourceManager.GetObject("LightBulb48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string NetworkAvailableText {
            get {
                return ResourceManager.GetString("NetworkAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network is currently available..
        /// </summary>
        internal static string NetworkAvailableToolTip {
            get {
                return ResourceManager.GetString("NetworkAvailableToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string NetworkNotAvailableText {
            get {
                return ResourceManager.GetString("NetworkNotAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network is currently not available..
        /// </summary>
        internal static string NetworkNotAvailableToolTip {
            get {
                return ResourceManager.GetString("NetworkNotAvailableToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap None48 {
            get {
                object obj = ResourceManager.GetObject("None48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no zones in the workspace to display smart parts..
        /// </summary>
        internal static string NoZonesInZoneWorkspace {
            get {
                return ResourceManager.GetString("NoZonesInZoneWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no zone named {0} to display the smart part in..
        /// </summary>
        internal static string NoZoneWithName {
            get {
                return ResourceManager.GetString("NoZoneWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Question48 {
            get {
                object obj = ResourceManager.GetObject("Question48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string QuestionCaption {
            get {
                return ResourceManager.GetString("QuestionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string QuitButton {
            get {
                return ResourceManager.GetString("QuitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string RecurrenceDailyEveryDay {
            get {
                return ResourceManager.GetString("RecurrenceDailyEveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days.
        /// </summary>
        internal static string RecurrenceDailyEveryNthDays {
            get {
                return ResourceManager.GetString("RecurrenceDailyEveryNthDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weekday.
        /// </summary>
        internal static string RecurrenceDailyEveryWeekDays {
            get {
                return ResourceManager.GetString("RecurrenceDailyEveryWeekDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weekend day.
        /// </summary>
        internal static string RecurrenceDailyEveryWeekendDays {
            get {
                return ResourceManager.GetString("RecurrenceDailyEveryWeekendDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs every {0} effective {1} from {2} to {3}.
        /// </summary>
        internal static string RecurrenceFormat {
            get {
                return ResourceManager.GetString("RecurrenceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day {0} of every month.
        /// </summary>
        internal static string RecurrenceMonthlyEveryMonth {
            get {
                return ResourceManager.GetString("RecurrenceMonthlyEveryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day {0} of every {1} months.
        /// </summary>
        internal static string RecurrenceMonthlyEveryNthMonths {
            get {
                return ResourceManager.GetString("RecurrenceMonthlyEveryNthMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} of every month.
        /// </summary>
        internal static string RecurrenceMonthNthEveryMonth {
            get {
                return ResourceManager.GetString("RecurrenceMonthNthEveryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} of every {2} months.
        /// </summary>
        internal static string RecurrenceMonthNthEveryNthMonths {
            get {
                return ResourceManager.GetString("RecurrenceMonthNthEveryNthMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} on {0}.
        /// </summary>
        internal static string RecurrenceWeeklyEveryNthWeek {
            get {
                return ResourceManager.GetString("RecurrenceWeeklyEveryNthWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string RecurrenceWeeklyEveryWeek {
            get {
                return ResourceManager.GetString("RecurrenceWeeklyEveryWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string RecurrenceYearly {
            get {
                return ResourceManager.GetString("RecurrenceYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} of {2}.
        /// </summary>
        internal static string RecurrenceYearNth {
            get {
                return ResourceManager.GetString("RecurrenceYearNth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string RetryButton {
            get {
                return ResourceManager.GetString("RetryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart part is not a control..
        /// </summary>
        internal static string SmartPartNotControl {
            get {
                return ResourceManager.GetString("SmartPartNotControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart part has not been shown previously by the current manager..
        /// </summary>
        internal static string SmartPartNotInManager {
            get {
                return ResourceManager.GetString("SmartPartNotInManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did You Know....
        /// </summary>
        internal static string TipOfTheDayFormDefaultTitle {
            get {
                return ResourceManager.GetString("TipOfTheDayFormDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace supports smart parts of type {0}..
        /// </summary>
        internal static string UnsupportedSmartPartType {
            get {
                return ResourceManager.GetString("UnsupportedSmartPartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Warning48 {
            get {
                object obj = ResourceManager.GetObject("Warning48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningCaption {
            get {
                return ResourceManager.GetString("WarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
    }
}
