//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowGroup.ServerModules {
    using System;
    using System.ComponentModel;
    using FlowGroup.Runtime.ObjectStore.DataTypes;
    
    public partial class Entity {
        public virtual GuidField ProductInformation {
            get {
                return ((GuidField)(this.GetProperty("ProductInformation")));
            }
            set {
                if ((this.ProductInformation != value)) {
                    this.SetProperty("ProductInformation", value);
                }
            }
        }
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public virtual double ProductByPrice {
            get {
                return ((double)(this.GetProperty("ProductByPrice", 0D)));
            }
            set {
                if ((this.ProductByPrice != value)) {
                    this.SetProperty("ProductByPrice", value);
                }
            }
        }
    }
}
