//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WmcSoft.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WmcSoft.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to find assembly {0}. Make sure it is installed in the guidance package Lib folder..
        /// </summary>
        internal static string AssemblyNotFound {
            get {
                return ResourceManager.GetString("AssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to locate guidance package install folder..
        /// </summary>
        internal static string ConfigurationServiceGuidancePackageNotFound {
            get {
                return ResourceManager.GetString("ConfigurationServiceGuidancePackageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #error Couldn&apos;t generate code.
        ////*
        ///{0}
        ///*/.
        /// </summary>
        internal static string CustomTool_GeneralError {
            get {
                return ResourceManager.GetString("CustomTool_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tool {0} does not contain the required {1} attribute..
        /// </summary>
        internal static string CustomTool_ToolRequiredAttributeMissing {
            get {
                return ResourceManager.GetString("CustomTool_ToolRequiredAttributeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to find Visual Studio registry hive root..
        /// </summary>
        internal static string HiveRootNotFound {
            get {
                return ResourceManager.GetString("HiveRootNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid Type..
        /// </summary>
        internal static string InvalidTypeError {
            get {
                return ResourceManager.GetString("InvalidTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter type {0} does not implement the required interface {1}..
        /// </summary>
        internal static string InvalidTypeFilter {
            get {
                return ResourceManager.GetString("InvalidTypeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ProjectMappingInformation xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; 
        ///													 xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; 
        ///													 FileName=&quot;ProjectMapping.xml&quot; 
        ///													 xmlns=&quot;http://schemas.microsoft.com/pag/project-mapping&quot;&gt;
        ///	&lt;ProjectMappingTables&gt;
        ///	&lt;/ProjectMappingTables&gt;
        ///&lt;/ProjectMappingInformation&gt;.
        /// </summary>
        internal static string MappingFileContent {
            get {
                return ResourceManager.GetString("MappingFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Project mapping already exists..
        /// </summary>
        internal static string ProjectMappingAlreadyExists {
            get {
                return ResourceManager.GetString("ProjectMappingAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The folder where the Project mapping resides must be named &apos;{0}&apos;..
        /// </summary>
        internal static string ProjectMappingFileNotFound {
            get {
                return ResourceManager.GetString("ProjectMappingFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Project mapping table already exists..
        /// </summary>
        internal static string ProjectMappingTableAlreadyExists {
            get {
                return ResourceManager.GetString("ProjectMappingTableAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Project mapping table not found..
        /// </summary>
        internal static string ProjectMappingTableNotFound {
            get {
                return ResourceManager.GetString("ProjectMappingTableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Project not found..
        /// </summary>
        internal static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à solution types.
        /// </summary>
        internal static string PublicNonSystemTypeFilter_Description {
            get {
                return ResourceManager.GetString("PublicNonSystemTypeFilter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à public and primitive types..
        /// </summary>
        internal static string PublicPrivateTypesFilter_Description {
            get {
                return ResourceManager.GetString("PublicPrivateTypesFilter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à public types.
        /// </summary>
        internal static string PublicTypesFilter_Description {
            get {
                return ResourceManager.GetString("PublicTypesFilter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type {0} is not public..
        /// </summary>
        internal static string PublicTypesFilter_Error {
            get {
                return ResourceManager.GetString("PublicTypesFilter_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot access closed registry key..
        /// </summary>
        internal static string RegistryKeyAccessorClosedKey {
            get {
                return ResourceManager.GetString("RegistryKeyAccessorClosedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to read name {0} in registry key {1}..
        /// </summary>
        internal static string RegistryKeyAccessorFailed {
            get {
                return ResourceManager.GetString("RegistryKeyAccessorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ServiceProvider is null..
        /// </summary>
        internal static string ServiceProviderIsNull {
            get {
                return ResourceManager.GetString("ServiceProviderIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Argument {0} value cannot be an empty string..
        /// </summary>
        internal static string StringCannotBeEmpty {
            get {
                return ResourceManager.GetString("StringCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type &apos;{0}&apos; must have the &apos;{1}&apos; attribute..
        /// </summary>
        internal static string Tool_AttributeMissing {
            get {
                return ResourceManager.GetString("Tool_AttributeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current project type can&apos;t have code elements, or can&apos;t compile to a .NET language. Supported project types are C# and VB.NET..
        /// </summary>
        internal static string Tool_NoCodeDomSupport {
            get {
                return ResourceManager.GetString("Tool_NoCodeDomSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can&apos;t get current project item..
        /// </summary>
        internal static string Tool_NoDTEProjectItem {
            get {
                return ResourceManager.GetString("Tool_NoDTEProjectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Success..
        /// </summary>
        internal static string Tool_Success {
            get {
                return ResourceManager.GetString("Tool_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Output of type CodeDom must be either a CodeNamespace or a CodeCompileUnit..
        /// </summary>
        internal static string Tool_UnsupportedCodeDomOutput {
            get {
                return ResourceManager.GetString("Tool_UnsupportedCodeDomOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current project type is unsupported for this tool..
        /// </summary>
        internal static string Tool_UnsupportedProjectType {
            get {
                return ResourceManager.GetString("Tool_UnsupportedProjectType", resourceCulture);
            }
        }
    }
}
